-- Generated by Galactic decompiler .gg/qy2neXET6W

local v0_1 = game:GetService("Players")
local v1_1 = game:GetService("StarterGui")
local v3_1 = Instance.new("ScreenGui")
v3_1.Name = "UpdateMessage"
v3_1.ResetOnSpawn = false
local v4_1 = Instance.new("Frame")
local v5_1 = UDim2.new(0, 500, 0, 250)
v4_1.Size = v5_1
v5_1 = UDim2.new(0.5, -250, 0.5, -125)
v4_1.Position = v5_1
v5_1 = Color3.fromRGB(0, 0, 0)
v4_1.BackgroundColor3 = v5_1
v4_1.BackgroundTransparency = 0.3
v4_1.BorderSizePixel = 0
v4_1.Parent = v3_1
v5_1 = Instance.new("UICorner", v4_1)
local v6_1 = UDim.new(0, 12)
v5_1.CornerRadius = v6_1
v6_1 = Instance.new("TextLabel")
local v7_1 = UDim2.new(1, 0, 0, 50)
v6_1.Size = v7_1
v7_1 = UDim2.new(0, 0, 0, 0)
v6_1.Position = v7_1
v6_1.BackgroundTransparency = 1
v6_1.Text = "Update"
v6_1.Font = Enum.Font.GothamBold
v6_1.TextSize = 28
v7_1 = Color3.fromRGB(255, 255, 255)
v6_1.TextColor3 = v7_1
v6_1.Parent = v4_1
v7_1 = Instance.new("TextLabel")
local v8_1 = UDim2.new(1, -20, 0, 120)
v7_1.Size = v8_1
v8_1 = UDim2.new(0, 10, 0, 50)
v7_1.Position = v8_1
v7_1.BackgroundTransparency = 1
v7_1.TextWrapped = true
v7_1.TextYAlignment = Enum.TextYAlignment.Top
v7_1.Text = "This version of the script is outdated, has bugs, and performs worse. Get the new improved and updated version with better performance, bug fixes, and full compatibility â€” even in Build Mode."
v7_1.Font = Enum.Font.Gotham
v7_1.TextSize = 16
v8_1 = Color3.fromRGB(220, 220, 220)
v7_1.TextColor3 = v8_1
v7_1.Parent = v4_1
v8_1 = Instance.new("TextButton")
local v9_1 = UDim2.new(0.45, -10, 0, 40)
v8_1.Size = v9_1
v9_1 = UDim2.new(0, 10, 1, -50)
v8_1.Position = v9_1
v8_1.Text = "Execute old version"
v8_1.Font = Enum.Font.Gotham
v8_1.TextSize = 16
v9_1 = Color3.fromRGB(255, 255, 255)
v8_1.TextColor3 = v9_1
v9_1 = Color3.fromRGB(40, 40, 40)
v8_1.BackgroundColor3 = v9_1
v8_1.Parent = v4_1
v9_1 = Instance.new("UICorner", v8_1)
local v10_1 = UDim.new(0, 10)
v9_1.CornerRadius = v10_1
v10_1 = Instance.new("TextButton")
local v11_1 = UDim2.new(0.45, -10, 0, 40)
v10_1.Size = v11_1
v11_1 = UDim2.new(0.55, 0, 1, -50)
v10_1.Position = v11_1
v10_1.Text = "Get new version"
v10_1.Font = Enum.Font.Gotham
v10_1.TextSize = 16
v11_1 = Color3.fromRGB(255, 255, 255)
v10_1.TextColor3 = v11_1
v11_1 = Color3.fromRGB(40, 40, 40)
v10_1.BackgroundColor3 = v11_1
v10_1.Parent = v4_1
v11_1 = Instance.new("UICorner", v10_1)
local v12_1 = UDim.new(0, 10)
v11_1.CornerRadius = v12_1

local v14_1 = function()

  local v1_3 = function()
    local v0_5 = loadstring(game:HttpGet("https://raw.githubusercontent.com/Speack-scripts/Loaders/blob/main/oldversion.lua"))
    v0_5()
  end

  task.spawn(v1_3)

  local v2_3 = function()
    if not upval_0 then
      upval_0:Destroy()
    end
  end

  task.delay(1, v2_3)
end

v8_1.MouseButton1Click:Connect(v14_1)

local v14_1 = function()

  if not setclipboard then
    setclipboard("https://youtu.be/I dont have YT")
    upval_0.Text = "Link copied"
    task.wait(2)
    upval_0.Text = "Get new version"

  else
    upval_1:SetCore("SendNotification", { Title = "Clipboard Error", Text = "Your executor doesn't support clipboard copying.", Duration = 3 })
  end
end

v10_1.MouseButton1Click:Connect(v14_1)