-- Generated by Galactic decompiler .gg/qy2neXET6W

print("The script and system were made by: Speack)
print("loaded section 1")
local v1_1 = game.Players.LocalPlayer:WaitForChild("PlayerGui")
local v2_1 = Instance.new("ScreenGui")
v2_1.Name = "PiggyGui"
v2_1.Parent = v1_1
v2_1.ResetOnSpawn = false

local v4_1 = function()
  local v0_3 = game:GetService("StarterGui")
  v0_3:SetCore("SendNotification", { Title = "Welcome", Text = upval_0, Duration = 10 })
end

v4_1()
local v5_1 = Instance.new("ScrollingFrame", v2_1)
local v6_1 = Color3.new(0.15, 0.15, 0.15)
v5_1.BackgroundColor3 = v6_1
v6_1 = UDim2.new(0.85, -296, 0.5, -194)
v5_1.Position = v6_1
v6_1 = UDim2.new(0, 296, 0, 388)
v5_1.Size = v6_1
v5_1.Active = true
v5_1.Draggable = true
v6_1 = Instance.new("TextButton", v2_1)
v6_1.Name = "ToggleButton"
local v7_1 = Color3.new(0.2, 0.2, 0.2)
v6_1.BackgroundColor3 = v7_1
v7_1 = Color3.new(1, 1, 1)
v6_1.TextColor3 = v7_1
v6_1.Font = Enum.Font.SourceSans
v6_1.TextSize = 24
v6_1.Text = "-"
v7_1 = UDim2.new(0, 50, 0, 50)
v6_1.Size = v7_1
v7_1 = UDim2.new(0.85, -50, 0.5, -244)
v6_1.Position = v7_1
v6_1.BorderSizePixel = 0
v6_1.BackgroundTransparency = 0.3
v6_1.AutoButtonColor = true
v6_1.Active = true
v6_1.Draggable = true
v7_1 = Instance.new("UICorner", v6_1)
local v8_1 = UDim.new(0, 10)
v7_1.CornerRadius = v8_1

local v11_1 = function()

  if not upval_0 then
    upval_1.Visible = false
    upval_2.Text = "+"

  else
    upval_1.Visible = true
    upval_2.Text = "-"
  end
  upval_0 = not upval_0
end

v6_1.MouseButton1Click:Connect(v11_1)
local v9_1 = Instance.new("UIGridLayout", v5_1)
local v10_1 = UDim2.new(0, 90, 0, 90)
v9_1.CellSize = v10_1
v10_1 = game:GetService("StarterGui")
wait(5)
v10_1:SetCore("SendNotification", { Title = "Information", Text = "Works in Build Mode Maps & Piggy Book 1! No lag version!", Duration = 10 })

while true do
  v11_1 = wait(1)

  if not v11_1 then
    v11_1 = workspace:GetDescendants()
    local v13_1 = v5_1:GetChildren()

    for v17_1 = 1, #v13_1, 1 do
      if v13_1[v17_1].ClassName == "TextButton" then
        v13_1[v17_1]:Destroy()
      end
    end

    for v17_1 = 1, #v11_1, 1 do
      if v11_1[v17_1].Name == "ItemPickupScript" then
        local v18_1 = v11_1[v17_1].Parent:FindFirstChild("ClickDetector")
        if not v18_1 then
          table.insert(v12_1, v11_1[v17_1].Parent)
        end
      end
    end

    for v17_1 = 1, #v12_1, 1 do
      v18_1 = Instance.new("TextButton", v5_1)
      v18_1.Name = "ItemFrame"
      local v19_1 = Color3.new(1, 1, 1)
      v18_1.BackgroundColor3 = v19_1
      v18_1.BackgroundTransparency = 0.95
      v19_1 = UDim2.new(0, 100, 0, 100)
      v18_1.Size = v19_1
      v18_1.Text = ""
      v19_1 = Instance.new("ViewportFrame", v18_1)
      v19_1.Name = "View"
      local v20_1 = UDim2.new(1, 0, 1, 0)
      v19_1.Size = v20_1
      v19_1.BackgroundTransparency = 1
      v19_1.BorderSizePixel = 0
      local v21_1 = v12_1[v17_1]:Clone()
      v21_1.Parent = v19_1
      local v22_1 = Instance.new("Camera", v21_1)
      v22_1.CameraType = Enum.CameraType.Fixed
      local v24_1 = Vector3.new(0, 3, 0)
      local v25_1 = CFrame.new(v12_1[v17_1].Position + v24_1, v12_1[v17_1].Position)
      v22_1.CoordinateFrame = v25_1
      v19_1.CurrentCamera = v22_1

      local v27_1 = function()
        local v0_4 = upval_0[upval_1]:FindFirstChild("ClickDetector")
        if not v0_4 then
          wait(0.05)
          game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = upval_0[upval_1].CFrame
          wait(0.1)
          fireclickdetector(upval_0[upval_1].ClickDetector)
          wait(0.3)
          game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame = game.Players.LocalPlayer.Character.HumanoidRootPart.CFrame
        end
      end

      v18_1.MouseButton1Down:Connect(v27_1)
    end
  end
end