-- Generated by Galactic decompiler .gg/qy2neXET6W

print("loaded section 2")
local v0_1 = game:GetService("StarterGui")
wait(5)
local v1_1 = game:GetService("StarterGui")
local v2_1 = game:GetService("Players")
local v4_1 = v2_1.LocalPlayer:WaitForChild("PlayerGui")
task.wait(duration)
local v5_1 = Instance.new("ScreenGui", v4_1)
v5_1.Name = "CreditsGui"
local v6_1 = Instance.new("Frame", v5_1)
local v7_1 = UDim2.new(0, 400, 0, 250)
v6_1.Size = v7_1
v7_1 = UDim2.new(0.5, -200, 0.5, -125)
v6_1.Position = v7_1
v7_1 = Color3.new(0.2, 0.2, 0.2)
v6_1.BackgroundColor3 = v7_1
v6_1.BackgroundTransparency = 0.3
v7_1 = Vector2.new(0.5, 0.5)
v6_1.AnchorPoint = v7_1
v7_1 = Instance.new("UICorner", v6_1)
local v8_1 = UDim.new(0, 10)
v7_1.CornerRadius = v8_1
v8_1 = Instance.new("TextLabel", v6_1)
local v9_1 = UDim2.new(1, 0, 0, 50)
v8_1.Size = v9_1
v9_1 = UDim2.new(0, 0, 0, 0)
v8_1.Position = v9_1
v8_1.BackgroundTransparency = 1
v8_1.Text = "Credits"
v8_1.Font = Enum.Font.SourceSansBold
v8_1.TextSize = 24
v9_1 = Color3.new(1, 1, 1)
v8_1.TextColor3 = v9_1
v9_1 = Instance.new("TextLabel", v6_1)
local v10_1 = UDim2.new(1, -20, 0, 100)
v9_1.Size = v10_1
v10_1 = UDim2.new(0, 10, 0, 50)
v9_1.Position = v10_1
v9_1.BackgroundTransparency = 1
v9_1.Text = "By _zxs. for more in discord."
v9_1.Font = Enum.Font.SourceSans
v9_1.TextSize = 18
v10_1 = Color3.new(1, 1, 1)
v9_1.TextColor3 = v10_1
v9_1.TextWrapped = true
v9_1.TextYAlignment = Enum.TextYAlignment.Top
v10_1 = Instance.new("TextButton", v6_1)
local v11_1 = UDim2.new(0, 150, 0, 40)
v10_1.Size = v11_1
v11_1 = UDim2.new(0.5, -160, 0.75, 0)
v10_1.Position = v11_1
v11_1 = Color3.new(0.3, 0.3, 0.3)
v10_1.BackgroundColor3 = v11_1
v10_1.Text = "Copy Discord"
v10_1.Font = Enum.Font.SourceSans
v10_1.TextSize = 18
v11_1 = Color3.new(1, 1, 1)
v10_1.TextColor3 = v11_1
v11_1 = Instance.new("UICorner", v10_1)
local v12_1 = UDim.new(0, 8)
v11_1.CornerRadius = v12_1

local v14_1 = function()
  setclipboard("https://discord.gg/g8D8f5Z6u6")
end

v10_1.MouseButton1Click:Connect(v14_1)
v12_1 = Instance.new("TextButton", v6_1)
local v13_1 = UDim2.new(0, 150, 0, 40)
v12_1.Size = v13_1
v13_1 = UDim2.new(0.5, 10, 0.75, 0)
v12_1.Position = v13_1
v13_1 = Color3.new(0.3, 0.3, 0.3)
v12_1.BackgroundColor3 = v13_1
v12_1.Text = "Copy YouTube"
v12_1.Font = Enum.Font.SourceSans
v12_1.TextSize = 18
v13_1 = Color3.new(1, 1, 1)
v12_1.TextColor3 = v13_1
v13_1 = Instance.new("UICorner", v12_1)
v14_1 = UDim.new(0, 8)
v13_1.CornerRadius = v14_1

local v16_1 = function()
  setclipboard("Go to discord")
end

v12_1.MouseButton1Click:Connect(v16_1)
v14_1 = Instance.new("TextButton", v6_1)
local v15_1 = UDim2.new(0, 40, 0, 40)
v14_1.Size = v15_1
v15_1 = UDim2.new(1, -45, 0, 5)
v14_1.Position = v15_1
v15_1 = Color3.new(0.5, 0, 0)
v14_1.BackgroundColor3 = v15_1
v14_1.Text = "10"
v14_1.Font = Enum.Font.SourceSansBold
v14_1.TextSize = 18
v15_1 = Color3.new(1, 1, 1)
v14_1.TextColor3 = v15_1
v15_1 = Instance.new("UICorner", v14_1)
v16_1 = UDim.new(1, 0)
v15_1.CornerRadius = v16_1

local v18_1 = function()

  for v3_4 = 10, 1, -1 do
    local v5_4 = tostring(v3_4)
    upval_0.Text = v5_4
    task.wait(1)
  end
  upval_0.Text = "X"
  upval_1 = true
end

task.spawn(v18_1)

local v19_1 = function()

  if not upval_0 then
    upval_1:Destroy()
  end
end

v14_1.MouseButton1Click:Connect(v19_1)