-- Generated by Galactic decompiler .gg/qy2neXET6W

print("The script and system were made by: Speack)
print("loaded section 1")
local v1_1 = game.Players.LocalPlayer:WaitForChild("PlayerGui")
local v2_1 = Instance.new("ScreenGui")
v2_1.Name = "PiggyGui"
v2_1.Parent = v1_1
v2_1.ResetOnSpawn = false
local v3_1 = game:GetService("StarterGui")
v3_1:SetCore("SendNotification", { Title = "Welcome", Text = "Enjoy! Script made by: Speack", Duration = 10 })
v3_1 = Instance.new("ScrollingFrame", v2_1)
local v4_1 = Color3.new(0.15, 0.15, 0.15)
v3_1.BackgroundColor3 = v4_1
v4_1 = UDim2.new(0.85, -296, 0.5, -194)
v3_1.Position = v4_1
v4_1 = UDim2.new(0, 296, 0, 388)
v3_1.Size = v4_1
v3_1.Active = true
v3_1.Draggable = true
v4_1 = Instance.new("TextButton", v2_1)
v4_1.Name = "ToggleButton"
local v5_1 = Color3.new(0.2, 0.2, 0.2)
v4_1.BackgroundColor3 = v5_1
v5_1 = Color3.new(1, 1, 1)
v4_1.TextColor3 = v5_1
v4_1.Font = Enum.Font.SourceSans
v4_1.TextSize = 24
v4_1.Text = "-"
v5_1 = UDim2.new(0, 50, 0, 50)
v4_1.Size = v5_1
v5_1 = UDim2.new(0.85, -50, 0.5, -244)
v4_1.Position = v5_1
v4_1.BorderSizePixel = 0
v4_1.BackgroundTransparency = 0.3
v4_1.AutoButtonColor = true
v4_1.Active = true
v4_1.Draggable = true
v5_1 = Instance.new("UICorner", v4_1)
local v6_1 = UDim.new(0, 10)
v5_1.CornerRadius = v6_1

local v9_1 = function()
  upval_0 = not upval_0
  upval_1.Visible = upval_0

  if not upval_0 then
    if "-" then
    else
    end
  end
  upval_2.Text = "+"
end

v4_1.MouseButton1Click:Connect(v9_1)
local v7_1 = Instance.new("UIGridLayout", v3_1)
local v8_1 = UDim2.new(0, 90, 0, 90)
v7_1.CellSize = v8_1
v8_1 = loadstring("loadstring(game:HttpGet('https://pastebin.com/raw/a5mSXxgH'))()")
v8_1()

while true do
  v8_1 = wait(1)

  if not v8_1 then
    local v9_1, v10_1, v11_1 = pairs(v3_1:GetChildren())

    while true do
      local v14_1 = v13_1:IsA("TextButton")
      if not v14_1 then
        v13_1:Destroy()
      end

      for v12_1, v13_1 in v9_1 do
      end
      local v9_1, v10_1, v11_1 = pairs(workspace:GetDescendants())

      while true do
        v14_1 = v13_1:IsA("Model")
        if v14_1 then
          v14_1 = v13_1:IsA("Part")
          if not v14_1 then
          else
            v14_1 = v13_1:FindFirstChild("ClickDetector")
            if v14_1 then
              v14_1 = v13_1:FindFirstChildOfClass("ProximityPrompt")
              if not v14_1 then
              else
                table.insert(v8_1, v13_1)
              end
            end
          end
        end

        for v12_1, v13_1 in v9_1 do
        end
        local v9_1, v10_1, v11_1 = pairs(workspace:GetChildren())

        while true do
          v14_1 = v13_1:IsA("Folder")
          if not v14_1 then
            v14_1 = tonumber(v13_1.Name)
            if not v14_1 then
              local v14_1, v15_1, v16_1 = pairs(v13_1:GetChildren())

              while true do
                local v19_1 = v18_1:FindFirstChild("ClickDetector")
                if v19_1 then
                  v19_1 = v18_1:FindFirstChildOfClass("ProximityPrompt")
                  if not v19_1 then
                  else
                    table.insert(v8_1, v18_1)
                  end
                end

                for v17_1, v18_1 in v14_1 do
                end
              end
            end

            for v12_1, v13_1 in v9_1 do
            end
            local v9_1, v10_1, v11_1 = pairs(v8_1)

            while true do
              v14_1 = v13_1:IsA("BasePart")
              if not v14_1 then
                if not v13_1.Position then
                  v14_1 = Instance.new("TextButton", v3_1)
                  v14_1.Name = "ItemFrame"
                  v15_1 = Color3.new(1, 1, 1)
                  v14_1.BackgroundColor3 = v15_1
                  v14_1.BackgroundTransparency = 0.95
                  v15_1 = UDim2.new(0, 100, 0, 100)
                  v14_1.Size = v15_1
                  if v13_1.Name then
                  end
                  v14_1.Text = "Unknown"
                  v15_1 = Instance.new("ViewportFrame", v14_1)
                  v15_1.Name = "View"
                  v16_1 = UDim2.new(1, 0, 1, 0)
                  v15_1.Size = v16_1
                  v15_1.BackgroundTransparency = 1
                  v15_1.BorderSizePixel = 0
                  v16_1 = v13_1:Clone()
                  v16_1.Parent = v15_1
                  v17_1 = Instance.new("Camera", v15_1)
                  v17_1.CameraType = Enum.CameraType.Fixed
                  v19_1 = Vector3.new(0, 3, 0)
                  local v20_1 = CFrame.new(v13_1.Position + v19_1, v13_1.Position)
                  v17_1.CFrame = v20_1
                  v15_1.CurrentCamera = v17_1

                  local v22_1 = function()
                    local v0_3 = upval_0:FindFirstChild("ClickDetector")
                    if not v0_3 then
                      wait(0.05)
                      upval_1.Character.HumanoidRootPart.CFrame = upval_0.CFrame
                      wait(0.1)
                      fireclickdetector(upval_0.ClickDetector)
                      wait(0.3)
                      upval_1.Character.HumanoidRootPart.CFrame = upval_1.Character.HumanoidRootPart.CFrame
                    else
                      v0_3 = upval_0:FindFirstChildOfClass("ProximityPrompt")
                      if not v0_3 then
                        v0_3 = upval_0:FindFirstChildOfClass("ProximityPrompt")
                        if not v0_3 then
                          wait(0.05)
                          upval_1.Character.HumanoidRootPart.CFrame = upval_0.CFrame
                          wait(0.1)
                          v0_3:InputHoldBegin()
                          wait(0.3)
                          v0_3:InputHoldEnd()
                          upval_1.Character.HumanoidRootPart.CFrame = upval_1.Character.HumanoidRootPart.CFrame
                        end
                      end
                    end
                  end

                  v14_1.MouseButton1Down:Connect(v22_1)
                end
              end

              for v12_1, v13_1 in v9_1 do
              end
            end
          end

        end

      end

    end

  end

end